

particle_filter_args:
  num_particles: 50
  ESS_threshold: 0.5


plotting_args:
  states_to_plot: [0]
  state_names: ['State']
  pars_to_plot: [0]
  par_names: ['Leak location']


prior_pars:
  type: 'uniform'
  lower_bound: [0.5]
  upper_bound: [1.5]
  num_pars: 1

model_type: 'latent'
backend: 'torch'

forward_model_args:
  num_skip_steps: 1
  PDE_step_size: 0.001        
  space_dim: 256
  x_max: 2
  batch_size: 256
  num_PDE_states: 1
  num_pars: 1
  initial_condition_path: data/burgers/initial_conditions
  matlab: False
  model_args:
    AE_model_type: 'WAE'
    AE_model_path: 'burgers_phase/autoencoders/WAE_8_latent_0.0001_consistency_0.001_channels_64_layers_4_trans_layers_2_embedding_64_vit'
    time_stepping_model_path: 'burgers_phase/time_steppers/transformer'
    preprocessor_path: 'burgers_phase/preprocessor.pkl'
    num_previous_steps: 16
    phase: 'burgers'

observation_args:
  noise_variance: 1.0e-2
  observation_times: [1, 300, 5]
  full_time_points: [0, 0.3, 300]

observation_operator_args:
  observation_state_ids: [0]
  observation_space_ids: [0, 256, 1]
  full_space_points: [0, 256, 256]

likelihood_args:
  noise_variance: 1.0e-2
  multivariate: False


model_error_args:
  state_noise_variance: 1.0e-7
  parameter_noise_variance: [1.0e-12]
  
