

particle_filter_args:
  num_particles: 500
  ESS_threshold: 0.5


plotting_args:
  states_to_plot: [0, 1]
  state_names: ['eta', 'phi']
  pars_to_plot: [0]
  par_names: ['Bar height']
  plot_bar: True

prior_pars:
  type: 'uniform'
  lower_bound: [0.07]
  upper_bound: [0.35]
  num_pars: 1

model_type: 'latent'
backend: 'torch'

forward_model_args:
  num_skip_steps: 1
  PDE_step_size: 0.03535
  space_dim: 512
  x_max: 25.6
  batch_size: 128
  num_PDE_states: 2
  num_pars: 1
  initial_condition_path: 'data/wave_submerged_bar/initial_conditions'
  matlab: True
  model_args:
    AE_model_type: 'WAE'
    AE_model_path: 'wave_phase/autoencoders/WAE'
    time_stepping_model_path: 'wave_phase/time_steppers/transformer'
    preprocessor_path: 'wave_phase/preprocessor.pkl'
    num_previous_steps: 16
    phase: 'wave'

observation_args:
  observation_file: 'data/wave_submerged_bar/observations/observations.csv'
  noise_variance: 5.0e-12
  observation_times: [100, 1100, 25]
  full_time_points: [0, 45, 1273]

observation_operator_args:
  observation_state_ids: [0]
  observation_space_ids: [79, 209, 269, 289, 313, 345, 379, 419]
  full_space_points: [0.05, 25.6, 512]

likelihood_args:
  noise_variance: 5.0e-3
  multivariate: True

model_error_args:
  state_noise_variance: 1.0e-1
  parameter_noise_variance: [1.0e-1]
  
