

particle_filter_args:
  num_particles: 1500
  ESS_threshold: 0.5

plotting_args:
  states_to_plot: [0, 1, 2]
  state_names: ['Hold up', 'Pressure', 'Velocity']
  pars_to_plot: [0, 1]
  par_names: ['Leak location', 'Leak size']

prior_pars:
  type: 'uniform'
  lower_bound: [10.0, 1.]
  upper_bound: [4990, 2.]
  num_pars: 2

model_type: 'PDE'

forward_model_args:
  model_args:
    basic_args:
      xmin: 0
      xmax: 5000
      num_elements: 200
      num_states: 3
      polynomial_order: 2
      polynomial_type: 'legendre'

    steady_state:
      newton_params:
          solver: 'direct'
          max_newton_iter: 200
          newton_tol: 1.0e-5
          num_jacobian_reuses: 120
            
    numerical_flux_args:
      type: 'lax_friedrichs'
      alpha: 0.5

    stabilizer_args:
      type: 'slope_limiter'
      second_derivative_upper_bound: 1.0e-8

    time_integrator_args:
      type: 'BDF2'
      step_size: 0.01
      newton_params:
        solver: 'direct'
        max_newton_iter: 200
        newton_tol: 1.0e-5
        num_jacobian_reuses: 600

    BC_args:
      type: 'dirichlet'
      treatment: 'naive'
      state_or_flux: {'left': 'flux', 'right': 'state'}

observation_args:
  noise_variance: 5.0e-5
  observation_times: [400, 800, 1200, 1600, 2000, 2400, 2800, 3200, 3600, 4000, 4400, 4800, 5200, 5600, 6000, 6400, 6800, 7200, 7600, 8000,]
                      # 8400, 8800, 9200, 9600, 10000, 10400, 10800, 11200, 11600, 12000, 12400, 12800, 13200, 13600, 14000, 14400, 14800, 15200, 
                      # 15600, 16000, 16400, 16800, 17200, 17600]
  full_time_points: [0, 180, 18000]

observation_operator_args:
  observation_state_ids: [1]
  observation_space_ids: [10, 250, 500]
  full_space_points: [0, 5000, 512]

likelihood_args:
  noise_variance: 1.0e-4

model_error_args:
  noise_variance: [1.0e-6, 1.0e-5, 1.0e-5]
  
