

particle_filter_args:
  num_particles: 30
  ESS_threshold: 0.5

prior_pars:
  type: 'uniform'
  lower_bound: [10.0, 0.0]
  upper_bound: [1990, 1.0]
  num_pars: 2

model_type: 'PDE'

forward_model_args:
  model_args:
    basic_args:
      xmin: 0
      xmax: 2000
      num_elements: 150
      num_states: 2
      polynomial_order: 2
      polynomial_type: 'legendre'

    steady_state:
      newton_params:
          solver: 'direct'
          max_newton_iter: 200
          newton_tol: 1.0e-5
          num_jacobian_reuses: 100
            
    numerical_flux_args:
      type: 'lax_friedrichs'
      alpha: 0.5

    stabilizer_args:
      type: 'slope_limiter'
      second_derivative_upper_bound: 1.0e-8

    time_integrator_args:
      type: 'BDF2'
      step_size: 0.01
      newton_params:
        solver: 'direct'
        max_newton_iter: 200
        newton_tol: 1.0e-5
        num_jacobian_reuses: 100

    BC_args:
      type: 'dirichlet'
      treatment: 'naive'
      state_or_flux: {'left': 'state', 'right': 'state'}

observation_args:
  noise_variance: 0.00001
  observation_times: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 
                      120, 130, 140, 150, 160, 170, 180, 190, 200]
  full_time_points: [0, 250, 25000]

observation_operator_args:
  observation_state_ids: [1]
  observation_space_ids: [20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240]
  full_space_points: [0, 2000, 256]

likelihood_args:
  noise_variance: 0.0001

model_error_args:
  noise_variance: 0.0001
  
