

particle_filter_args:
  num_particles: 250
  ESS_threshold: 0.5

prior_pars:
  type: 'uniform'
  lower_bound: [10.0, 1.0]
  upper_bound: [990, 3.0]
  num_pars: 2

model_type: 'PDE'

forward_model_args:
  model_args:
    basic_args:
      xmin: 0
      xmax: 1000
      num_elements: 75
      num_states: 2
      polynomial_order: 2
      polynomial_type: 'legendre'

    steady_state:
      newton_params:
          solver: 'direct'
          max_newton_iter: 200
          newton_tol: 1.0e-5
          num_jacobian_reuses: 100
            
    numerical_flux_args:
      type: 'lax_friedrichs'
      alpha: 0.5

    stabilizer_args:
      type: 'slope_limiter'
      second_derivative_upper_bound: 1.0e-8

    time_integrator_args:
      type: 'implicit_euler'
      step_size: 0.05
      newton_params:
        solver: 'direct'
        max_newton_iter: 200
        newton_tol: 1.0e-5
        num_jacobian_reuses: 100

    BC_args:
      type: 'dirichlet'
      treatment: 'naive'
      state_or_flux: {'left': 'state', 'right': 'state'}

observation_args:
  noise_variance: 3000
  observation_times: [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000, 3200, 3400]
  full_time_points: [0, 180, 3600]

observation_operator_args:
  observation_state_ids: [0]
  observation_space_ids: [10, 246]
  full_space_points: [0, 1000, 256]

likelihood_args:
  noise_variance: 6000

model_error_args:
  noise_variance: [1.0e-6, 1.0e-4]
  
