

particle_filter_args:
  num_particles: 30
  ESS_threshold: 0.5

prior_pars:
  type: 'uniform'
  lower_bound: [10.0, 1.0]
  upper_bound: [990, 3.0]
  num_pars: 2

model_type: 'neural_network'

forward_model_args:
  num_skip_steps: 4
  step_size: 0.05
  space_dim: 256
  x_max: 1000
  model_args:
    AE_model_type: 'WAE'
    AE_model_path: 'single_phase/autoencoders/WAE'
    time_stepping_model_path: 'single_phase/time_steppers/transformer'
    preprocessor_path: 'single_phase/preprocessor.pkl'
    num_previous_steps: 16
    phase: 'multi'

observation_args:
  noise_variance: 0.00001
  observation_times: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 
                      120, 130, 140, 150, 160, 170, 180, 190, 200]
  full_time_points: [0, 250, 25000]

observation_operator_args:
  observation_state_ids: [1]
  observation_space_ids: [20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240]
  full_space_points: [0, 2000, 256]

likelihood_args:
  noise_variance: 0.0001

model_error_args:
  noise_variance: 0.0001
  
