particle_filter_args:
  num_particles: 15
  ESS_threshold: 0.5

plotting_args:
  states_to_plot: [0, 1, 2]
  state_names: ['Hold up', 'Pressure', 'Velocity']
  pars_to_plot: [0, 1]
  par_names: ['Leak location', 'Leak size']
  observations_names: ['Pressure']

prior_pars:
  type: 'uniform'
  lower_bound: [10.0, 1.]
  upper_bound: [4990, 2.]
  num_pars: 2

model_type: 'PDE'
backend: 'numpy'

forward_model_args:
  num_PDE_states: 3
  model_args:
    basic_args:
      xmin: 0
      xmax: 5000
      num_elements: 500
      num_states: 3
      polynomial_order: 2
      polynomial_type: 'legendre'

    steady_state:
      newton_params:
          solver: 'direct'
          max_newton_iter: 200
          newton_tol: 1.0e-5
          num_jacobian_reuses: 100
            
    numerical_flux_args:
      type: 'lax_friedrichs'
      alpha: 0.5

    stabilizer_args:
      type: 'slope_limiter'
      second_derivative_upper_bound: 1.0e-8

    time_integrator_args:
      type: 'BDF2'
      step_size: 0.01
      newton_params:
        solver: 'direct'
        max_newton_iter: 200
        newton_tol: 1.0e-5
        num_jacobian_reuses: 600

    BC_args:
      type: 'dirichlet'
      treatment: 'naive'
      state_or_flux: {'left': 'flux', 'right': 'state'}

observation_args:
  noise_variance: 5.0e-5
  observation_times: [400, 4000, 400]
  full_time_points: [0, 180, 18000]

observation_operator_args:
  observation_state_ids: [1]
  observation_space_ids: [50, 100,  150, 200,  250, 300, 350, 400,  450]
  full_space_points: [0, 5000, 512]

likelihood_args:
  noise_variance: 1.0e-4
  multivariate: True

model_error_args:
  noise_variance: [1.0e-9, 1.0e-9, 1.0e-9]
  
